import { type LucideIcon, Award, Users, TrendingUp, Zap, CheckCircle, Rocket, Cog, Globe, Smartphone, Package, Building2, Laptop, Target, BarChart3, Mail, Phone, MapPin, Clock, Send, Bot, User, Sparkles, Linkedin, Instagram, MessageSquare, ArrowRight, Star, Play, Pause, ChevronLeft, ChevronRight, Lightbulb, Briefcase, DollarSign, Scale } from 'lucide-react'

export const Icons = {
  Award: Award,
  Users: Users,
  TrendingUp: TrendingUp,
  Zap: Zap,
  CheckCircle: CheckCircle,
  Rocket: Rocket,
  Cog: Cog,
  Globe: Globe,
  Smartphone: Smartphone,
  Package: Package,
  Building2: Building2,
  Laptop: Laptop,
  Target: Target,
  BarChart3: BarChart3,
  Mail: Mail,
  Phone: Phone,
  MapPin: MapPin,
  Clock: Clock,
  Send: Send,
  Bot: Bot,
  User: User,
  Sparkles: Sparkles,
  Linkedin: Linkedin,
  Instagram: Instagram,
  MessageSquare: MessageSquare,
  ArrowRight: ArrowRight,
  Star: Star,
  Play: Play,
  Pause: Pause,
  ChevronLeft: ChevronLeft,
  ChevronRight: ChevronRight,
  Lightbulb: Lightbulb,
  Briefcase: Briefcase,
  DollarSign: DollarSign,
  Scale: Scale,
}

export type Icon = LucideIcon
